# X Sentiment Analysis Configuration
# Central configuration file for all application settings

# =================================================================
# Sentiment Analysis Configuration
# =================================================================
sentiment:
  algorithm: "openai"  # Options: keyword, openai, vader
  
  # OpenAI/OpenRouter Configuration
  openai:
    provider: "openrouter"
    api_base_url: "https://openrouter.ai/api/v1"
    model: "meta-llama/llama-3.1-8b-instruct"  # Cheapest option
    temperature: 0.3
    max_tokens: 200
    timeout_seconds: 30
    max_retries: 3
    max_api_calls_per_run: 10  # Ultra safe limit
    
    system_prompt: |
      You are a financial sentiment analyst. Analyze tweets and assign a Fear & Greed score from 0-100.
      
      SCORING GUIDE:
      
      0-20 (EXTREME FEAR / PANIC):
      - "Bitcoin crashes to $110,000!" = 0-10
      - "$21B liquidation in one day" = 0-15
      - "Biggest flush in recent history" = 5-15
      - "MSTR crashing! Sell everything NOW!"
      - Predictions of major losses, panic selling
      - Multiple fear emojis (📉💀🔻)
      
      20-40 (FEAR):
      - "What to do...?" during volatility = 25-30
      - "Retest at $112k" (cautious technical) = 30-35
      - "MSTR risky right now, be careful"
      - "Tread lightly", cautious warnings
      - Concerns about downsides
      
      40-60 (NEUTRAL):
      - "BlackRock buying the dip" (defensive move) = 40-45
      - "We monetize volatility" (strategy statement) = 50
      - "MSTR trading at $150.30" (pure facts)
      - Balanced analysis, no clear bias
      - Questions without opinion
      
      60-80 (GREED):
      - "MSTR bullish, buying more"
      - "Good time to accumulate"
      - Clear buying signals, optimism
      
      80-100 (EXTREME GREED / EUPHORIA):
      - "MSTR to the moon! 🚀🚀🚀"
      - "This will 100x! Last chance!"
      - FOMO language, extreme predictions
      - Multiple rocket/fire emojis
      
      EDGE CASES (IMPORTANT):
      - "Buying the dip" during crash = 40-50 (defensive, NOT bullish)
      - "Massive liquidation" = 0-20 (extreme fear)
      - "Crashes to [price]" = 0-10 (extreme fear)
      - "What to do?" during volatility = 25-35 (uncertainty/fear)
      - "Biggest wipeout/flush" = 5-15 (extreme fear)
      - Institutional buying during crash = 40-50 (cautious, not greed)
      - Technical analysis during crash = 30-40 (cautious)
      
      IMPORTANT:
      - Detect sarcasm (often means opposite sentiment)
      - Consider emoji context heavily
      - "HODL", "diamond hands" = high greed (75-85)
      - "Dump", "exit now" = high fear (15-35)
      - Liquidations/wipeouts are ALWAYS extreme fear (0-20)
      - Price crashes are ALWAYS extreme fear (0-15)
      
      RESPONSE FORMAT (JSON only):
      {
        "score": 0-100,
        "reasoning": "brief 1-sentence explanation"
      }
  
  # Keyword Matching Configuration
  keyword:
    bullish_keywords:
      - "moon"
      - "bullish"
      - "buy"
      - "pump"
      - "rocket"
      - "🚀"
      - "up"
      - "gain"
      - "accumulate"
      - "long"
      - "calls"
    bearish_keywords:
      - "dump"
      - "bearish"
      - "sell"
      - "crash"
      - "down"
      - "loss"
      - "exit"
      - "short"
      - "puts"
  
  # VADER Configuration
  vader:
    threshold_positive: 0.05
    threshold_negative: -0.05

# =================================================================
# Bot Detection Configuration
# =================================================================
bot_detection:
  algorithm: "heuristic"  # Options: heuristic, openai
  
  # Heuristic-based Detection
  heuristic:
    follower_threshold: 100
    following_ratio_threshold: 5.0
    account_age_threshold_days: 30
    min_tweets_threshold: 10
    default_profile_pic_penalty: 0.3
    no_bio_penalty: 0.2
  
  # OpenAI/OpenRouter-based Detection
  openai:
    provider: "openrouter"
    api_base_url: "https://openrouter.ai/api/v1"
    model: "meta-llama/llama-3.1-8b-instruct"
    temperature: 0.1
    max_tokens: 150
    timeout_seconds: 30
    max_retries: 3
    
    system_prompt: |
      You are a social media bot detection specialist.
      
      Analyze Twitter/X account characteristics to determine if an account is likely a bot.
      
      BOT INDICATORS (increase bot likelihood):
      - Generic usernames (random numbers/letters)
      - Very low or very high follower/following ratio
      - New account with high activity
      - Repetitive posting patterns
      - Generic or missing bio
      - Promotional/spam content
      - Excessive hashtags or mentions
      
      HUMAN INDICATORS (decrease bot likelihood):
      - Verified account
      - Established account (>1 year old)
      - Balanced follower/following ratio
      - Personal bio with specific interests
      - Varied content and engagement
      - Conversational replies
      
      RESPONSE FORMAT (JSON only):
      {
        "is_bot": true|false,
        "confidence": 0.0-1.0,
        "reasoning": "brief 1-sentence explanation"
      }

# =================================================================
# Data Collection Configuration
# =================================================================
collection:
  query: "MSTR"
  max_results: 10
  schedule:
    - "Monday"
    - "Wednesday"
    - "Friday"
    - "Sunday"
  time_window_hours: 72

# =================================================================
# Dashboard Configuration
# =================================================================
dashboard:
  fear_greed_scale:
    min: 0
    max: 100
  default_days: 90
  thresholds:
    extreme_fear: 25
    fear: 40
    neutral_low: 40
    neutral_high: 60
    greed: 75
    extreme_greed: 100

# =================================================================
# API Configuration
# =================================================================
api:
  rate_limit:
    requests_per_15min: 1
    requests_per_day: 100
  retry:
    max_attempts: 3
    backoff_seconds: 60
