openapi: 3.0.3
info:
  title: X Sentiment Analysis API
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /sentiment/trends:
    get:
      summary: Get sentiment trends
      parameters:
        - in: query
          name: topic
          required: true
          schema:
            type: string
            enum: [Bitcoin, MSTR, BitcoinTreasuries]
        - in: query
          name: days
          required: false
          schema:
            type: integer
            default: 30
        - in: query
          name: algorithm
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Trend data
  /sentiment/daily:
    get:
      summary: Get daily aggregate sentiment
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: topic
          required: true
          schema:
            type: string
            enum: [Bitcoin, MSTR, BitcoinTreasuries]
      responses:
        '200':
          description: Daily aggregates
